### ISSUE TITLE
Menu no linux

### ISSUE THREAD

**Issue by arthurflor23** [cb130felix/Projeto-Otatop#2]
Menu não tá aparecendo no linux. Windows tá de boa.
 -> Não tá escrevendo nada dentro do <div id="menu"> no body da página.

**Comment by cb130felix** [comment]
Qual a treta mesmo? Tem que inverter as barras? Qual que é aceita no linux? "/' ou "\"?

**Comment by arthurflor23** [comment]
Acho que aqui pega qualquer uma, porém o mozilla só apareceu com "/"

**Comment by cb130felix** [comment]
Ok, problema resolvido! :dancer:
